# Generated by Django 4.0.3 on 2022-03-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudmodel',
            name='modelget',
        ),
        migrations.AddField(
            model_name='crudmodel',
            name='mycrud',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
